### ISSUE TITLE
Design Updates

### ISSUE THREAD

**Issue by dngrhm** [dngrhm/TabStache#11]
Looking for some updates on improving the face of the extension before releasing to as an "official" extension.

**Comment by collnwalkr** [comment]
@dngrhm I can take a shot at it. Take a look at the mockup I've attached to this comment and let me know what you think!

![sample ui](https://cloud.githubusercontent.com/assets/7200683/19096281/eb8182bc-8a4f-11e6-9395-699fc487d62e.png)

**Comment by collnwalkr** [comment]
These changes are in PR #13

**Comment by dngrhm** [comment]
Huge improvement! thanks for the PR
