### ISSUE TITLE
Ignore New Tab

### ISSUE THREAD

**Issue by dngrhm** [dngrhm/TabStache#3]
When storing a stache, ignore common tabs that would likely be duplicates (about:blank, extensions, apps, ...)

**Comment by KayvanMazaheri** [comment]
created a PR here : #5

**Comment by jvdub** [comment]
Also created a PR: #6

**Comment by dngrhm** [comment]
I like the dup checking and addition of chrome-extension in #5 and putting the validity check in a function in #6 I merged #5 and would greatly appreciate merging the conflicts into #6 

@jvdub feel free to resubmit as a new PR instead of merging the conflicts if you'd prefer.
