### ISSUE TITLE
JS cleanup

### ISSUE THREAD

**Issue by dngrhm** [dngrhm/TabStache#8]
This was first written when I was still new at JS.  The code could use some cleanup.  (for loops?).  Please submit PRs in smaller chunks.

**Comment by ZCoderGuy** [comment]
would you mind if i took a shot at this?

**Comment by andarilhoz** [comment]
I did some refactoring to ecma6 on this issue, but as ZCoderGuy is taking a look on that (and also asked before i could do it xP) i'll stop my refactoring and leave the fun part to him

**Comment by dngrhm** [comment]
Thanks devs! I merged #12.  Some good ecma6 improvements. @ZCoderGuy have at it

**Comment by ZCoderGuy** [comment]
Nevermind @andarilhoz  I dont have any time to do this. Something has come up and it sounds like you already have some stuff done. Good luck!

**Comment by andarilhoz** [comment]
So @dngrhm can i be in charge of this issue?
